iTwin/imodel-transformer

- .azure-pipelines/generate-docs.yaml
- change/@itwin-imodel-transformer-93119d94-d98c-4c8c-a5a8-50efb0348e41.json
- package.json
- packages/test-app/package.json
- packages/transformer/package.json
- pnpm-lock.yaml
Upgrade typedoc and typescript dependencies. We'll need the overrides until @itwin/build-tools is re-published.
> Docs - TypeScript 5 support

- packages/performance-tests/test/setup.ts
Only error out when both .env file is missing and CI is not set
> Don't error out on missing .env

- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
The old implementation of `forEachTrackedElement` querried both target and source iModels at the same time. It also ordered both querries by FederationGuid. This does not fork for the hybrid (ExternalSourceAspect & FederationGuid) approach because some elements were "acquiring" their federation guids during the initial transformation and the provenance for them was lost because both query results were out of order between each other (an element without fed guid in source query was placed in a different place because it was ordered by its "acquired" federationGuid in the target query).
This caused the transformer to enter an infinite recursion loop when processing element references.
(process inserted element -> process its parent (which already was inserted during initial transformation, …
> Fixed an infinite recursion bug when processing changes

- packages/test-app/src/Transformer.ts
- packages/transformer/src/IModelExporter.ts
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/IModelTransformerUtils.ts
- packages/transformer/src/test/TestUtils/TimelineTestUtil.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
- propagate new export/processChanges options types through to `ChangedInstanceIds.initialize`
> propagate new export/processChanges options types through to ChangedInstanceIds.initialize

- change/@itwin-imodel-transformer-6c797333-afb8-406b-afe2-be3b8bdb78e6.json
- packages/transformer/src/IModelCloneContext.ts
I had to change `Id64.isInvalid` to `!Id64.EntityReferences`, because `Id64.isInvalid` sees "e0" as valid id.
The problem was, that `IModelCloneContext` was trying to find relationship's target or source element that does not exist in the target iModel. So when `findTargetEntityId` returns "e0" for element referenced by relationship it would pass if statement with `Id64.isInvalid` and transformer would crash because `ECSqlStatement.bindId` can't bind invalid64Id.
Now `IModelCloneContext.findTargetEntityId` will return invalid id for target iModel relationship.
> IModelCloneContext.findTargetEntityId fixed relationship id finding

- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
`forEachTrackedElement` method iterates through related (tracked) elements in 2 imodels and invokes a callback on each pair.
There are 2 scenarios for iterating through tracked elements during transformer initialization.
1. Provenance is stored in target: Source ----> Target (prov)
2. Provenance is stored in source: Source (prov) ----> Target
These 2 scenarios only matter when the provenance is tracked by `ExternalSourceAspects` since depending on the provenance location the `element.id` and `identifier` fields will be switched.
When provenance is tracked by federation guids we don't care where the provenance is, because the callback should always be invoked in the data flow direction and not the provenance direction.
Methods that depend on the remap table (e.g. `findTargetElementId`) …
> Fix element provenance direction in reverse synchronization workflow

- packages/performance-tests/test/rawInserts.ts
switch from camel case to full words for info section of reporter. This now matches the other tests.
> Fix info syntax to match other tests

- change/@itwin-imodel-transformer-8b752da1-1170-408d-8866-6f0c21f09d02.json
- packages/transformer/src/BigMap.ts
- packages/transformer/src/EntityMap.ts
- packages/transformer/src/PendingReferenceMap.ts
- packages/transformer/src/transformer.ts
When transforming iModels with huge amounts of Element Aspects process can crash.
BigMap implementation will decrease performance by little bit.
To decrease memory usage, we can use https://www.npmjs.com/package/lmdb
> Start using BigMap instead of regular Map

- change/@itwin-imodel-transformer-d19ae39b-d3bd-40b4-9258-ea5b3e9bec05.json
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/TestUtils/IModelTestUtils.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
"Missing Id: error deleting model" error:
Added a fix and test for "Missing Id: error deleting model" which occured because onDeleteModel deleted definition model. It shouldn't delete definition model in onDeleteModel if its partition element will also be deleted, because elementTreeDeleter deletes definition model while deleting definition partition element.
"ForeignKey Constraint: error deleting model" error:
Added a fix and test for this error. Transformer tries to delete models before it deletes elements. Definition models cannot be deleted unless all of their modeled elements are deleted first.
> Fixed onDeleteModel "Missing Id" and "ForeignKey constraint" errors

- change/@itwin-imodel-transformer-f333a974-ba76-439f-8059-001157e9a47c.json
- packages/transformer/src/BranchProvenanceInitializer.ts
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
forwardport of https://github.com/iTwin/imodel-transformer/pull/120
> revert to original behavior of provenance ExternalSourceAspect version [fed guid branch]

- change/@itwin-imodel-transformer-757752b3-83a4-446f-9476-1c894ad16d9f.json
- packages/transformer/src/DetachedExportElementAspectsStrategy.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
This PR fixes a problem where aspect class has SQLite reserved keyword as its name. If EC class name has SQLite reserved keyword as its name, the class name must be quoted `SELECT * FROM schema.[SQLiteReservedKeyword]`
> Fix aspect queries when class name is reserved SQLite keyword

- packages/transformer/src/IModelTransformer.ts
Added methods that allow derived transformer classes to query synchronization version and provenance Scope aspect.
- Federation guid branch is not backwards compatible when it comes to supporting old branches. Exposing api to access scope aspect is necessary so that derived classes can fake the synchronization version themselves.
- Exporting TargetScopeProvenanceJsonProps for derived classes to make sense of 'Scope' aspect's jsonProps.
- explicitly calling `initialize` will throw errors if scope provenance is not initialized in change processing workflow. Exposed `initScopeProvenance` to derived classes.
> Added API for querying provenance info for derived transformer classes

- packages/transformer/src/IModelImporter.ts
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
This change allows processing of changes where Element CodeValues have been switched with one another
> Handle duplicate code values when updating elements

- packages/transformer/src/IModelTransformer.ts
Windows has a max total path limit of 260 and there can be schemas which don't reach the max path segment size, but the full path reaches max total path limit in windows systems.
> Add fix to handle max path limit in windows

- change/@itwin-imodel-transformer-7cdc44b9-db85-4875-bce6-36e8cd9a001a.json
- package.json
- packages/test-app/src/ElementUtils.ts
- packages/transformer/package.json
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/TestUtils/IModelTestUtils.ts
- packages/transformer/src/test/standalone/IModelTransformerResumption.test.ts
- pnpm-lock.yaml
> Handle max path limit on windows for schema names (backport)

- packages/performance-tests/test/iModelUtils.ts
- packages/transformer/src/test/IModelTransformerUtils.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
- pnpm-lock.yaml
- scripts/update_deps.sh
- Ignore fed guids on always present element ids when comparing imodels in tests
- closeIModel() + closeFile()
- script to only update locked itwin deps
- bump locked itwin dev deps
> 4.3.3 support

- change/@itwin-imodel-transformer-e3cb3820-f8ac-4f7b-bb7d-8f41018c5ecf.json
- packages/transformer/src/BigMap.ts
- packages/transformer/src/test/standalone/BigMap.test.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
Closes https://github.com/iTwin/imodel-transformer/issues/134
- Changed BigMap to implement Map instead of extending it. Implemented missing methods.
- Added BigMap tests.
- Added iModelTransformer test to verify that unresolved references are logged correctly. Moved logger initialization logic to beforeEach(), as it is reconfigured in new test case.
> Implemented missing methods in BigMap 

- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/IModelTransformerUtils.ts
- packages/transformer/src/test/TestUtils/IModelTestUtils.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
As https://github.com/iTwin/imodel-transformer/issues/149
Make root subject special cased when remapping from source to target
Fixed the bug on transformer side instead of native side as transformer is the only consumer of the corresponding native code
> Special case root subject remapping 

- change/@itwin-imodel-transformer-65f20003-2531-4208-a318-5b5a9fbc5ee1.json
- packages/transformer/src/IModelTransformer.ts
PR in 4.6.0 which made this change: https://github.com/iTwin/itwinjs-core/pull/6643/files
> Fix failing test which fails in 4.6.0 only due to a change in the way we handle deletions of DefinitionContainers

- change/@itwin-imodel-transformer-6d5fba74-5711-471e-9f99-4ef766c48902.json
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
Support providing the reversesync and sync versions when unsafe-migrate is set. This is to support svcs team and their use cases so they no longer have to have code surrounding this. A change we made to make syncDirection determined automatically by the transformer has made some of their patches no longer work.
I also ran into a bug when trying to test this which had 2 issues, the first being the hasElementChangedCache was getting aspect ids added to it. I believe it was ALWAYS supposed to be only element ids, but I made that mistake when converting to use Affan's changeset reader. The query that used to be used for the hasElementChangedCache had a where clause:  [`ic.ChangedInstance.ClassId IS (ONLY BisCore.Element)`](https://github.com/iTwin/imodel-transformer/commit/576295137997aa8911e5 …
> Support providing the reversesync and sync versions when unsafe-migrate is set.

- change/@itwin-imodel-transformer-359b2d25-3f51-4eab-b5d4-a6602ba69819.json
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/TestUtils/TimelineTestUtil.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
Leaving the responsibility up to the consumer. We already require them to download the iModels and acquire locks themselves, so we should also let them push changes as pushing changes releases locks. 
There have also been mentions of some transforms intentionally inserting data that isn't meant to be transformed back over, which would not be possible if we pushed changes for consumers, because then they wouldn't be able to add that data as part of the pending changeset indices.
> Revert "save and push changes after transformer is complete (#153)"

- change/@itwin-imodel-transformer-53ad9100-036c-41c0-83b9-d954608888cf.json
- packages/transformer/src/IModelImporter.ts
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
fix iTwin/imodel-transformer#177
set the default value of skipPropagateChangesToRootElements to be true
> skipPropagateChangesToRootElements should be default true

- .vscode/launch.json
- packages/performance-tests/test/cases/prepare-fork.ts
When fed guid opt branch was merged there was a change in initializeBranchProvenance() function which closed the master and branch imodel if createFedGuidsForMaster: true,. Because of this when the test tried to peform saveChanges() it would fail.
I decided to just remove save changes because performing .close() on the imodels should save changes before closing. This should be better for the context of a perf test so time isn't wasted reopening the imodel just to save changes and then close again.
> fix prepare-fork.ts

- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
- In an effort to replace internal apis that are currently deprecated and will be removed in itwin js 5.0 release, we found an alternative implementation for `nativeDb.extractChangedInstanceIdsFromChangeSets`.
-  `ChangedInstanceIds.initialize` extracts the changed instance ids and returns it. 
- This is used in our IModelTransformerHub tests
> replace nativedb extractChangedInstanceIdsFromChangeSets

- change/@itwin-imodel-transformer-9ed49a07-59ed-4232-99e0-f7b895aa8d4e.json
- packages/transformer/package.json
- packages/transformer/src/test/TestUtils/SchemaTestUtils.ts
- packages/transformer/src/test/TestUtils/index.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
- pnpm-lock.yaml
- Add SchemaTestUtils class that with schemaToXmlString method
- To convert schema to an xml string I added @itwin/ecschema-locaters as they have helper to do this
- In an effort to replace internal apis that are currently deprecated and will be removed in itwin js 5.0 release, we will replace `nativeDb.schemaToXmlString` with `SchemaTestUtils.schemaToXmlString`
> Replace native schemaToXmlString 

- change/@itwin-imodel-transformer-70f1f73f-ad6a-4ee1-adb2-41372b822905.json
- packages/transformer/src/ECReferenceTypesCache.ts
- packages/transformer/src/test/assets/TestQueryView.ecschema.xml
- packages/transformer/src/test/standalone/ECReferenceTypesCache.test.ts
- packages/transformer/src/test/standalone/IModelTransformer.test.ts
ECView elements are not "real" data and transformer does not need to process them. Relationships that point to an ECView instance are only allowed on ECView elements themselves, hence we don't need to track these relationships.
> Ignore navigational properties that point to an ECView

- change/@itwin-imodel-transformer-d641f741-5460-4382-91ac-8e82a71922c1.json
- packages/transformer/src/IModelExporter.ts
- packages/transformer/src/test/standalone/ChangedInstanceIds.test.ts
Custom changes API was unintentionally modifying a set passed by user, added a fix to create deep copy before doing modifications.
Fixes #251
> Fix for custom changes API to create a deep copy of `set` before modifying it.

- change/@itwin-imodel-transformer-238628a9-908f-4557-a4c4-ac7bce1032a4.json
- packages/transformer/src/IModelExporter.ts
- packages/transformer/src/test/standalone/IModelTransformerHub.test.ts
Fixed exporting custom changes when source has no change sets.
Fixes #257
Added a separate issue to discuss if this fall back is at all necessary #259
> Fix for exporting custom changes when iModel has no changesets.

- change/@itwin-imodel-transformer-02446d05-5e05-4b3b-a64c-26b127724749.json
- common/api/imodel-transformer.api.md
- packages/transformer/src/IModelExporter.ts
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/GeoLocationTransform.test.ts
Creates transform that can be applied to spatial elements when cloning a src imodel into target with different ECEF locations.
> Transform Linearly Located Imodels

- change/@itwin-imodel-transformer-8282633a-0288-4a06-9d23-800bce71d0c6.json
- common/api/imodel-transformer.api.md
- packages/transformer/src/IModelTransformer.ts
- packages/transformer/src/test/standalone/GeoLocationTransform.test.ts
If src and target imodel's have differing local Helmert transforms, transform target elements positions to maintain proper local positions.
The target imodel "additionalTransform" will always be maintained, even if it is null. The source imodel when copied into the target will have a combination of both helmert transforms applied to its elements placements. This way the result will place the elements in a position that when the targets "additionalTransform" is applied it will be in the correct geographic position. If the target's "additionalTransform" is null, then the we are simply applying the src's helmert transform permanently to each elements position instead of just at render time. If the src and target have different non null transforms, then the resulting transform applied to the …
> Allow Performing Transforms with additionalTransforms
